### PR TITLE
Fix appliance documentation formatting (Issue #102)

### LINKED ISSUE #102: Fix appliance documentation
#### Description
All of our appliances attempt to have a little table that shows input and output formats, but it's misformatted and renders as a header.

image

### PR DESCRIPTION
**Pull request by hawkinsw**
## Description

Input and output table formatting in README.md files of each appliance
misrender in Github-flavored MD. This commit fixes that issue.

Issue #102

## Due Diligence Checklist
- [x] Tests
- [x] Documentation
- [x] Consolidated commits
- [ ] Relevant labels assigned
- [ ] Changelog(s) updated

## Steps to Test
1. `yarn test`

## Deploy Notes
N/A

## Related Issues
Resolves #102

### CODE REVIEW

**Comment by slifty** [comment]
Thank you for this!

Very minor request before merge: could you edit the commit message so that `Issue #102` is at the *end* of the message instead of in the subject?

**Review by slifty — CHANGES_REQUESTED** [review]
Thank you so much for this!

Very minor request before merge: could you edit the commit message so that `Issue #102` is at the end of the message instead of in the subject?

Here is a commit message for an example of what I mean: https://github.com/tvkitchen/appliances/commit/f6529376f2e120d449262628b94186c918bdcab4

**Comment by hawkinsw** [comment]
> Thank you so much for this!
> 
> Very minor request before merge: could you edit the commit message so that `Issue #102` is at the end of the message instead of in the subject?
> 
> Here is a commit message for an example of what I mean: [f652937](https://github.com/tvkitchen/appliances/commit/f6529376f2e120d449262628b94186c918bdcab4)

Let me know what you think of this!!

**Review by slifty — APPROVED** [review]
Woot!

**Pull request merged**
